name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Chạy mỗi 5 phút

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request to Keep App Alive
        run: curl -I https://your-app-name.streamlit.app
